# Generated by Django 3.0.7 on 2020-06-16 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import pathManagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('relax', 'Relax'), ('didattica', 'Didattica'), ('esplorazione', 'Esplorazione'), ('escursionismo', 'Escursionismo')], max_length=30)),
                ('start', models.CharField(choices=[('bagnodiromagna', 'Bagno di Romagna'), ('sanpietroinbagno', 'San Pietro in Bagno'), ('acquapartita', 'Acquapartita'), ('laghi', 'Laghi'), ('alfero', 'Alfero')], max_length=30)),
                ('end', models.CharField(choices=[('bagnodiromagna', 'Bagno di Romagna'), ('sanpietroinbagno', 'San Pietro in Bagno'), ('acquapartita', 'Acquapartita'), ('laghi', 'Laghi'), ('alfero', 'Alfero')], max_length=30)),
                ('gradient', models.IntegerField()),
                ('walkTime', models.PositiveIntegerField()),
                ('bikeTime', models.PositiveIntegerField(blank=True, default=0)),
                ('carriageablePath', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nonCarriageablePath', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalKilometers', models.FloatField(blank=True, default='0', editable=False)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile')], max_length=30)),
                ('difficultyImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('context', multiselectfield.db.fields.MultiSelectField(choices=[('collinare', 'Collinare'), ('urbano', 'Urbano'), ('fluviale', 'Fluviale'), ('boschivo', 'Boschivo'), ('laghi', 'Laghi')], max_length=40)),
                ('contextImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('transport', multiselectfield.db.fields.MultiSelectField(choices=[('automobile', 'Automobile'), ('bicidacittà', 'Bici da città'), ('piedi', 'Piedi'), ('mountainbike', 'Mountain bike')], max_length=41)),
                ('transportImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('audience', multiselectfield.db.fields.MultiSelectField(choices=[('famiglia', 'Famiglia'), ('gruppi', 'Gruppi'), ('coppie', 'Coppie'), ('mobilitàridotta', 'Mobilità ridotta'), ('escursionisti', 'Escursionisti'), ('sportivi', 'Sportivi')], max_length=61)),
                ('audienceImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('path', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('cover', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathManagement.Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.Profile')),
            ],
            options={
                'unique_together': {('path', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ListPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=pathManagement.models.user_review_directory_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathManagement.Review')),
            ],
        ),
    ]
