# Generated by Django 3.0.7 on 2020-06-09 14:46

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import pathManagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('relax', 'Relax'), ('didattica', 'Didattica'), ('esplorazione', 'Esplorazione'), ('escursionismo', 'Escursionismo')], max_length=30)),
                ('start', models.CharField(choices=[('bagnodiromagna', 'Bagno di Romagna'), ('sanpietroinbagno', 'San Pietro in Bagno'), ('acquapartita', 'Acquapartita'), ('laghi', 'Laghi'), ('alfero', 'Alfero')], max_length=30)),
                ('end', models.CharField(choices=[('bagnodiromagna', 'Bagno di Romagna'), ('sanpietroinbagno', 'San Pietro in Bagno'), ('acquapartita', 'Acquapartita'), ('laghi', 'Laghi'), ('alfero', 'Alfero')], max_length=30)),
                ('gradient', models.IntegerField()),
                ('walkTime', models.PositiveIntegerField()),
                ('bikeTime', models.PositiveIntegerField(blank=True, default=0)),
                ('carriageablePath', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('nonCarriageablePath', models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalKilometers', models.FloatField(blank=True, default='0', editable=False)),
                ('difficulty', multiselectfield.db.fields.MultiSelectField(choices=[('facile', 'Facile'), ('medio', 'Medio'), ('difficile', 'Difficile')], max_length=22)),
                ('difficultyImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('context', multiselectfield.db.fields.MultiSelectField(choices=[('collinare', 'Collinare'), ('urbano', 'Urbano'), ('fluviale', 'Fluviale'), ('boschivo', 'Boschivo'), ('laghi', 'Laghi')], max_length=40)),
                ('contextImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('transport', multiselectfield.db.fields.MultiSelectField(choices=[('automobile', 'Automobile'), ('bicidacittà', 'Bici da città'), ('piedi', 'Piedi'), ('mountainbike', 'Mountain bike')], max_length=41)),
                ('transportImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('audience', multiselectfield.db.fields.MultiSelectField(choices=[('famiglia', 'Famiglia'), ('gruppi', 'Gruppi'), ('coppie', 'Coppie'), ('mobilitàridotta', 'Mobilità ridotta'), ('escursionisti', 'Escursionisti'), ('sportivi', 'Sportivi')], max_length=61)),
                ('audienceImage', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
                ('path', models.ImageField(upload_to=pathManagement.models.user_directory_path)),
            ],
        ),
    ]
