# Generated by Django 3.0.7 on 2020-06-09 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='bikeTime',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='path',
            name='carriageablePath',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='path',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='path',
            name='nonCarriageablePath',
            field=models.FloatField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='path',
            name='walkTime',
            field=models.PositiveIntegerField(),
        ),
    ]
