# Generated by Django 3.0.7 on 2020-06-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='updated_at',
        ),
    ]
