# Generated by Django 3.0.7 on 2020-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='activity',
            field=models.CharField(choices=[('relax', 'Relax'), ('didattica', 'Didattica'), ('esplorazione', 'Esplorazione'), ('escursionismo', 'Escursionismo'), ('sportivo', 'Sportivo')], max_length=30),
        ),
    ]
