# Generated by Django 3.0.7 on 2020-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathManagement', '0002_auto_20200618_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
    ]
