# Generated by Django 3.0.6 on 2020-06-12 09:14

from django.db import migrations, models
import django.db.models.deletion
import pathManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('pathManagement', '0002_remove_review_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path',
            options={'ordering': ['id']},
        ),
        migrations.CreateModel(
            name='ListPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to=pathManagement.models.user_review_directory_path)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathManagement.Review')),
            ],
        ),
    ]
