# Generated by Django 3.0.7 on 2020-06-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
