# Generated by Django 3.0.7 on 2020-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user_<property object at 0x03D1E9D8>@default.com', max_length=254, unique=True),
        ),
    ]
