# Generated by Django 3.0.7 on 2020-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user_<property object at 0x7fe1d5f9b278>@default.com', max_length=254, unique=True),
        ),
    ]
