# Generated by Django 3.0.6 on 2020-06-12 09:14

from django.db import migrations, models
import userManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_auto_20200611_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static\\img\\baseAvatar.png', upload_to=userManagement.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user_<property object at 0x03C968C0>@default.com', max_length=254, unique=True),
        ),
    ]
