# Generated by Django 3.0.7 on 2020-06-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_auto_20200612_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user_<property object at 0x043CE9D8>@default.com', max_length=254, unique=True),
        ),
    ]
