# Generated by Django 3.0.7 on 2020-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_auto_20200615_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user_<property object at 0x7f4ae4264408>@default.com', max_length=254, unique=True),
        ),
    ]
